### ISSUE TITLE
Entrer une nouvelle membre honoraire

### ISSUE THREAD

**Issue by CFHR2018** [samueldrouin/PyGuide#51]
Je ne suis pas capable de te copier les codes défectueux. Je vais donc devoir t'envoyer des textes 
à chaque fois.

Lorsque j'ajoute de nouvelles membres, le logiciel me dit qu'il n'est pas capable de communiquer avec la base de données. Les informations sont tout de même sauvegardées dans la base de données. Elles ne sont pas visibles tout de suite. Il faut faire une nouvelle recherche pour les voir.

**Comment by samueldrouin** [comment]
UNIQUE constraint failed: participante.prenom, participante.nom, participante.telephone_1 Unable to fetch row

**Comment by samueldrouin** [comment]
Je ne suis pas capable de reproduire l'erreur : l'ajout de nouvelle participante et le changement de statut de membre fonctionne bien sur ma base de donnée. 

Si l'erreur arrive à nouveau peux-tu m'envoyer la base de données par courriel pour que je puisse tenter de reproduire l'erreur (le sujet doit inclure PyGuide ainsi que le numéro du bug (#51)).
