### ISSUE TITLE
Groupe non membre

### ISSUE THREAD

**Issue by CFHR2018** [samueldrouin/PyGuide#59]
Quand on clique sur Groupe, tous les groupes apparaissent. Y a-t-il moyen d'y voir seulement les activités qui entrent dans cette catégorie? Par exemple, en cochant une case à cet effet lorsque l'on inscrit une nouvelle activité?

**Comment by samueldrouin** [comment]
Je préfère la flexibilité que l'option actuelle permet (avoir à la fois des membres et des groupes pour une même activité). Il est aussi possible d'utiliser la barre de recherche pour trouver une activité.  L'implantation de cette option serait probablement un peu complexe parce que je devrais ajouter une manière de corriger les erreurs (quelqu'un entre une activité dans la mauvaise catégorie) pour tous les cas suivants :
- Groupe -> Non groupe
- Groupe avec valeur déjà entrées -> Non groupe
- Non groupe -> groupe
- Non groupe avec inscription -> groupe

Je ne crois donc pas que je vais implanter cette fonction.
