### ISSUE TITLE
Renouvelement du membership

### ISSUE THREAD

**Issue by CFHR2018** [samueldrouin/PyGuide#60]
Lorsque je veux renouveler le membership d'une personne, python arrête systématiquement de fonctionner. Je dois fermer le programme.

Y a-t-il moyen de changer les dates de renouvellement si le Centre choisit que chaque membership dure un an plutôt que de tous les renouveler à la même date?

**Comment by samueldrouin** [comment]
Le bug provient de Qt. La mise à jour à 5.11.2 règle le problème.
