### ISSUE TITLE
Statistiques

### ISSUE THREAD

**Issue by CFHR2018** [samueldrouin/PyGuide#61]
Lorsque je demande d'afficher les statistiques dans Excel, Python cesse de fonctionner.

Je vais pouvoir mieux tester les statistiques lorsque tu auras eu le temps de faire les autres corrections. Il manque des données pour pouvoir tester cette partie puisque des données de d'autres modules n'ont pas pu être enregistrées.

**Comment by samueldrouin** [comment]
Quel est la version d'Excel ?

**Comment by CFHR2018** [comment]
La version de 2013.

**Comment by samueldrouin** [comment]
Le problème n'est probablement pas lié à Excel mais plutôt à la requête effectuée. Pourrais-tu m'indiquer les paramètres de la requête ?

**Comment by samueldrouin** [comment]
Corrigé par la nouvelle mise à jour.
