### ISSUE TITLE
Redémarrer lors de l'entrée d'une nouvelle participante

### ISSUE THREAD

**Issue by CFHR2018** [samueldrouin/PyGuide#64]
Erreur lors de la connection. La connection avec la base de données n'a pas pu être établie. Voici ce qui est indiqué lorsque je veux ajouter une nouvelle membre ou une nouvelle participante. L'information est tout de même entrée, je peux la voir en fermant la base de données quand je l'ouvre de nouveau.

**Comment by samueldrouin** [comment]
La participante est déjà créée lors de l'inscription ce qui cause l'erreur lorsqu'on essaye de la créer un deuxième fois.

Correction : Lors de l'inscription on enregistre le membre, ferme le dialog et ouvre celui pour modifier.

**Comment by samueldrouin** [comment]
ATTENTION : L'enregistrement du membre doit ce faire lors de l'enregistrement de l'inscription et non lors de l'ouverture du dialog comme actuellement !!
